### ISSUE TITLE
ImportError: cannot import name 'override' from 'typing' (/usr/lib/python3.10/typing.py)

### ISSUE THREAD

**Issue by My-Random-Thoughts** [Szwendacz99/BookStack-Python-exporter#11]
Full Error:
```
    Traceback (most recent call last):
      File "~/BookStackBackup/exporter.py", line 10, in <module>
        from typing import Dict, List, Union, override
    ImportError: cannot import name 'override' from 'typing' (/usr/lib/python3.10/typing.py)

```

Commnad:
`    python3 ~/BookStackBackup/exporter.py -t ~/BookStackBackup/token.txt -H http://home.lan:8080 -f html -p ~/BookStackBackup/
`

**Comment by Szwendacz99** [comment]
Thanks, I forget to check older pythons compatibility, fix is already in repo and latest release. If somethings is still broken, let me know.

**Comment by My-Random-Thoughts** [comment]
All working again, thanks for the quick fix.
