### ISSUE TITLE
option to respect rate limits

### ISSUE THREAD

**Issue by dirks** [Szwendacz99/BookStack-Python-exporter#5]
By default the bookstack api allows up to 180 requests per minute per user, see https://demo.bookstackapp.com/api/docs#rate-limits.

I am currently running into this limit and it would be nice if the client, i.e. BookStack-Python-exporter would have an option to limit the number of request per minute, maybe with a default value identical to the default of the bookstack api.

**Comment by Szwendacz99** [comment]
Fix is present in latest commit and version 1.4.1.
If something is still not right with following rate limit, pls reopen the issue with problem description.
